server:
  port: 8080

spring:
  application:
    name: api-gateway
  webflux:
    httpclient:
      ssl:
        useInsecureTrustManager: true
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://book-service-production-c5b7.up.railway.app
          predicates:
            - Path=/api/books/**
        - id: order-service
          uri: http://order-service-production-bfde.up.railway.app
          predicates:
            - Path=/api/orders/**
        - id: user-service
          uri: http://user-service-production-02c9.up.railway.app
          predicates:
            - Path=/api/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
